### ISSUE TITLE
Kurzreview

### ISSUE THREAD

**Issue by signalwerk** [niciwatri/portfolio#1]
## Hallo Nicole
Ich habe mir kurz dein Portfolio durchgeschaut. Ich habe nur kurz drauf geschaut, da ich davon ausgehe, dass du noch nicht fertig bist. Hier vielleicht ein paar Inputs (eher technisch):

* Du hast jetzt etwa 90 Zeichen pro Zeile. Ist eher lang. Vielleicht einfach der Grundtext noch ein Px grösser?
* Ist die Unterstreichung bei den Untertiteln richtig/wichtig. Wirkt jetzt zu wenig grafisch. Könnte mit der häufig gesehenen Unterstreichung eines Links verwechselt werden. Eventuell mehr abstand zum Text (Unterlängen werden auch durchstrichen) und vielleicht noch dicker?
* Bitte schaue deine Gedankenstrich noch mal an. Du machst jetzt ein Divis. Schau mal [heir](https://github.com/logrinto/webtypo/wiki/Divis-vs.-Halbgeviert)
* Kannst du den Text noch verdichten oder stärker strukturieren um den Leser besser zu führen?
* Heine Titel (H6) wirken weniger wichtig als deine Bild-Legenden. Oder verstehe ich etwas falsch?
* Zeilenabstand in der Navigation eventuell noch erhöhen
* Vielleicht das Projekt zuerst dann der Unterricht?

Wenn du einen  Kommentar oder ein Problem hast, bitte hier antworten.

**Comment by niciwatri** [comment]
Hallo Stefan,

Vielen Dank für dein Feedback.

Bin dabei die Punkte anzupassen und den Text zu überarbeiten.
Nun bin ich mir bei zwei Punkten die du aufgezählt hast nicht sicher.
1. Ich habe bereits Halbgeviertstriche anstelle von Divis eingefügt. Oder hab ich einen übersehen?
2. Wie meinst du den Text verdichten oder stärker strukturieren? Da ich schon 3 Hierarchiestufen habe möchte ich sicher nicht noch mehr... Vielleicht wird es ja schon besser sobald ich den Text überarbeitet habe. Schliesslich kann man vieles noch kürzen. Hoffe das passt dann so?

Danke nochmals
LG Nicole

**Comment by signalwerk** [comment]
1. Hmm... Vielleicht wars auch nur eines. Da ist mir wohl [dieses](https://github.com/niciwatri/portfolio/commit/af5dbb0685a753adaf2b7b94a554846b0a3bc25d#diff-eacf331f0ffc35d4b482f1d15a887d3bL273) ins Auge gesprungen. Aber das ist jetzt ja fort. Kleinlich ich weiss... 🙈
2. Ich finde du hast genügend Hierarchiestufen. Was ich damit meinte; Du hast relativ viel Text erarbeitet. Das finde ich grundsätzlich gut und auch die Struktur hast du mit der Hierarchie erstellt. Jedoch ist ein selektives Lesen nun fast nicht mehr möglich. Entweder ich lese alles oder du hast die Personen verloren.


<hr>

Kleines Beispiel:

## Hauptema Küchengeräte
### Kochtopf
#### Vorteile
blablablabla ....
### Bratpfanne
#### Nachteile
blablablabla ....

Wenn ich nun zum Abschnitt «Nachteile» scrolle, so ist es für mich eventuell schwierig zu Verstehen, dass wir nun über Küchengeräte und nun die Nachteile der Bratpfanne bearbeiten.

<hr>

Ein Kleines Beispiel aus deinem Text: Es gibt nun Zum Beispiel einen Titel «Die Aufgabenstellung». Angenommen mich spricht nun das Bild an und ich lese kurz oben und unten. So verstehe ich nun eigentlich nicht, dass dies die Aufgabenstellung der menschlichen Kamera im Unterricht ist. Die Hierarchie hilft mir hier nicht, da «Die Aufgabenstellung» optisch gleich erscheint als «Menschliche Kamera». Wenn du aber eine Struktur eher so hast:


<hr>

## Unterricht
### Aufgabe – Menschliche Kamera

![02_experiment_bild-text_flip_kl](https://user-images.githubusercontent.com/992878/34609933-0a9bbdec-f21f-11e7-8299-87f828305930.jpg)

blablablabla ....

<hr>

So kann auch ein selektives Lesen erleichtert werden ohne deine Hierarchie zu verstehen.

Aber das sind Kleinigkeiten. Ich finde du hast dir sehr viel Mühe gegeben mit dem Text und natürlich kann man auch den Anspruch haben, dass sich jemand damit befasst 😉

**Comment by niciwatri** [comment]
Ok alles klar. Nun verstehe ich was du meinst. Mal schauen ob ich noch einen Weg finde dies zu lösen. Scheint mir jetzt, da ich alles schon geschrieben habe, als eher schwierig.

Danke nochmals und bis bald.


Am 05.01.2018 um 13:52 schrieb Stefan Huber <notifications@github.com<mailto:notifications@github.com>>:


  1.  Hmm... Vielleicht wars auch nur eines. Da ist mir wohl dieses<https://github.com/niciwatri/portfolio/commit/af5dbb0685a753adaf2b7b94a554846b0a3bc25d#diff-eacf331f0ffc35d4b482f1d15a887d3bL273> ins Auge gesprungen. Aber das ist jetzt ja fort. Kleinlich ich weiss... 🙈
  2.  Ich finde du hast genügend Hierarchiestufen. Was ich damit meinte; Du hast relativ viel Text erarbeitet. Das finde ich grundsätzlich gut und auch die Struktur hast du mit der Hierarchie erstellt. Jedoch ist ein selektives Lesen nun fast nicht mehr möglich. Entweder ich lese alles oder du hast die Personen verloren.

________________________________

Kleines Beispiel:

Hauptema Küchengeräte
Kochtopf
Vorteile

blablablabla ....

Bratpfanne
Nachteile

blablablabla ....

Wenn ich nun zum Abschnitt «Nachteile» scrolle, so ist es für mich eventuell schwierig zu Verstehen, dass wir nun über Küchengeräte und nun die Nachteile der Bratpfanne bearbeiten.

________________________________

Ein Kleines Beispiel aus deinem Text: Es gibt nun Zum Beispiel einen Titel «Die Aufgabenstellung». Angenommen mich spricht nun das Bild an und ich lese kurz oben und unten. So verstehe ich nun eigentlich nicht, dass dies die Aufgabenstellung der menschlichen Kamera im Unterricht ist. Die Hierarchie hilft mir hier nicht, da «Die Aufgabenstellung» optisch gleich erscheint als «Menschliche Kamera». Wenn du aber eine Struktur eher so hast:

________________________________
Unterricht
Aufgabe – Menschliche Kamera

[02_experiment_bild-text_flip_kl]<https://user-images.githubusercontent.com/992878/34609933-0a9bbdec-f21f-11e7-8299-87f828305930.jpg>

blablablabla ....

________________________________

So kann auch ein selektives Lesen erleichtert werden ohne deine Hierarchie zu verstehen.

Aber das sind Kleinigkeiten. Ich finde du hast dir sehr viel Mühe gegeben mit dem Text und natürlich kann man auch den Anspruch haben, dass sich jemand damit befasst 😉
